- name: Adding aliases
  loop: "{{ aliases | dict2items }}"
  lineinfile:
    path: /etc/hosts
    line: "{{ item.value }} {{ item.key }}"

- name: Allow SSH password authentication
  lineinfile:
    path: '/etc/ssh/sshd_config'
    line: 'PasswordAuthentication yes'
    regexp: '^#?PasswordAuthentication'
  register: password_auth

- name: Restart sshd service
  service:
    name: sshd
    state: restarted
  when: password_auth is changed

- name: Setup root account password
  user:
    name: root
    password: '$6$wEz0MHKHK/cjuU3l$3BQWREyYZ1KmWfCjqqB5ZQ/freMTsRp3YOSGDX4QnelxDChkqfCd0H3z6.c4j7a076j0DokebwLmgRvwgKSeU.' # toor

- name: Add zip's password to the fasttrack wordlist
  lineinfile:
      path: /usr/share/wordlists/fasttrack.txt
      line: IhateMyJob

- name: Create /root/hacking directory
  file:
    path: /root/hacking
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Copy and rename the wordlist to /root/hacking
  copy:
      src: /usr/share/wordlists/fasttrack.txt
      dest: /root/hacking/wordlist.txt
      owner: root
      mode: 0640
      remote_src: yes

- name: Remove all other wordlists from /usr/share
  file:
      path: "/usr/share/wordlists/{{ item }}"
      state: absent
  with_items:
    -  dirb
    -  dirbuster
    -  fern-wifi
    -  metasploit
    -  nmap.lst
    -  wfuzz
    -  rockyou.txt.gz


- name: Copy file fcrackzip with owner and permissions
  copy:
      src: ../files/fcrackzip_1.0-10_amd64.deb
      dest: /tmp/fcrackzip_1.0-10_amd64.deb
      owner: root
      group: root
      mode: '0644'

- name: Install fcrackzip deb package
  apt:
      deb: /tmp/fcrackzip_1.0-10_amd64.deb
