- name: kypo-user-access
  src: https://gitlab.ics.muni.cz/muni-kypo-crp/backend-python/ansible-networking-stage/kypo-user-access.git
  scm: git
  version: 39a4f935

- name: sandbox-logging
  src: https://gitlab.ics.muni.cz/muni-kypo/ansible-roles/sandbox-logging.git
  scm: git
  version: 5431051c

- name: chrony
  src: https://gitlab.ics.muni.cz/muni-kypo/ansible-roles/chrony.git
  scm: git
  version: 1.0.1
