- name: kypo-user-access
  src: https://gitlab.ics.muni.cz/muni-kypo-crp/backend-python/ansible-networking-stage/kypo-user-access.git
  scm: git
  version: 39a4f935

- name: sandbox-logging-bash
  src: https://gitlab.ics.muni.cz/muni-kypo/ansible-roles/sandbox-logging-bash.git
  scm: git
  version: 1.0.5

- name: sandbox-logging-forward
  src: https://gitlab.ics.muni.cz/muni-kypo/ansible-roles/sandbox-logging-forward.git
  scm: git
  version: 1.0.2

- name: chrony
  src: https://gitlab.ics.muni.cz/muni-kypo/ansible-roles/chrony.git
  scm: git
  version: 1.0.1
