- name: kypo-user-access
  src: git@gitlab.ics.muni.cz:muni-kypo-crp/backend-python/ansible-networking-stage/kypo-user-access.git
  scm: git


- name: sandbox-logging-bash
  src: git@gitlab.ics.muni.cz:muni-kypo/ansible-roles/sandbox-logging-bash.git
  scm: git
  version: 1.0.0

- name: sandbox-logging-forward
  src: git@gitlab.ics.muni.cz:muni-kypo/ansible-roles/sandbox-logging-forward.git
  scm: git
  version: 1.0.0

- name: chrony
  src: git@gitlab.ics.muni.cz:muni-kypo/ansible-roles/chrony.git
  scm: git
  version: 1.0.0
